sudo: false

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

# before_install:
#   - pip install --user cpp-coveralls

script:
  - cmake -H. -Bbuild
  - cd build
  - cmake --build .
  - ctest

# after_success:
#   - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: true
