sudo: false

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

script:
  - cmake -H. -Bbuild
  - cd build
  - cmake --build .
  - ./bin/unit_tests

notifications:
  email: true
