sudo: false

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - pip install --user cpp-coveralls

script:
  - ./configure --enable-gcov
  - cmake -H. -Bbuild
  - cd build
  - cmake --build .
  - ./bin/unit_tests

after_success:
  - coveralls --root .. --exclude ".*external.*" --exclude ".*CMakeFiles.*" --exclude "*build*" --exclude "*Doxumentation*" --exclude "*Examples*" --exclude "*cmake/*" --exclude "*Tests*"

notifications:
  email: true
