sudo: false

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - pip install --user cpp-coveralls

script:
  - cmake -H. -Bbuild
  - cmake --build build
  - ./build/bin/unit_tests

after_success:
  - coveralls --root . --exclude "*Examples*" --exclude "*Parallel*" --exclude "*build*"

notifications:
  email: true
