mkdir Project/Parallel/Data
mkdir Project/Parallel/Data/Final
mkdir Project/Parallel/Data/Final/Auxiliary
mkdir Project/Parallel/Data/Final/Conserved
mkdir Project/Parallel/Data/Final/Primitive
mkdir Project/Parallel/Data/Final/Constants
mkdir Project/Parallel/Data/Final/Domain
mkdir Project/Parallel/Data/TimeSeries
mkdir Project/Parallel/Data/TimeSeries/Auxiliary
mkdir Project/Parallel/Data/TimeSeries/Conserved
mkdir Project/Parallel/Data/TimeSeries/Constants
mkdir Project/Parallel/Data/TimeSeries/Primitive
mkdir Project/Parallel/Data/TimeSeries/UserDef

mkdir Project/Serial/Data
mkdir Project/Serial/Data/Final
mkdir Project/Serial/Data/Final/Auxiliary
mkdir Project/Serial/Data/Final/Conserved
mkdir Project/Serial/Data/Final/Primitive
mkdir Project/Serial/Data/Final/Constants
mkdir Project/Serial/Data/Final/Domain
mkdir Project/Serial/Data/TimeSeries
mkdir Project/Serial/Data/TimeSeries/Auxiliary
mkdir Project/Serial/Data/TimeSeries/Conserved
mkdir Project/Serial/Data/TimeSeries/Constants
mkdir Project/Serial/Data/TimeSeries/Primitive
mkdir Project/Serial/Data/TimeSeries/UserDef

mkdir Tests/TestData
mkdir Tests/TestData/Parallel
mkdir Tests/TestData/Parallel/Auxiliary
mkdir Tests/TestData/Parallel/Conserved
mkdir Tests/TestData/Parallel/Constants
mkdir Tests/TestData/Parallel/Primitive

mkdir Tests/TestData/Serial
mkdir Tests/TestData/Serial/Auxiliary
mkdir Tests/TestData/Serial/Conserved
mkdir Tests/TestData/Serial/Constants
mkdir Tests/TestData/Serial/Primitive

mkdir Examples/Data
mkdir Examples/Data/Final
mkdir Examples/Data/Final/Auxiliary
mkdir Examples/Data/Final/Conserved
mkdir Examples/Data/Final/Primitive
mkdir Examples/Data/Final/Constants
mkdir Examples/Data/Final/Domain
mkdir Examples/Data/TimeSeries
mkdir Examples/Data/TimeSeries/Auxiliary
mkdir Examples/Data/TimeSeries/Conserved
mkdir Examples/Data/TimeSeries/Constants
mkdir Examples/Data/TimeSeries/Primitive
mkdir Examples/Data/TimeSeries/UserDef
