rm Data/TimeSeries/Primitive/*
rm Data/TimeSeries/Conserved/*
rm Data/TimeSeries/Auxiliary/*
rm Data/TimeSeries/Constants/*
rm Data/Final/Primitive/*
rm Data/Final/Conserved/*
rm Data/Final/Auxiliary/*
rm Data/Final/Constants/*
rm Data/TimeSeries/UserDef/*
