var annotated_dup =
[
    [ "Args", "structArgs.html", "structArgs" ],
    [ "BackRKArguments", "classBackRKArguments.html", "classBackRKArguments" ],
    [ "BackwardsRK2", "classBackwardsRK2.html", "classBackwardsRK2" ],
    [ "Bcs", "classBcs.html", "classBcs" ],
    [ "BrioWuTwoFluid", "classBrioWuTwoFluid.html", "classBrioWuTwoFluid" ],
    [ "CPAlfvenWaveSingleFluid", "classCPAlfvenWaveSingleFluid.html", "classCPAlfvenWaveSingleFluid" ],
    [ "CPAlfvenWaveTwoFluid", "classCPAlfvenWaveTwoFluid.html", "classCPAlfvenWaveTwoFluid" ],
    [ "CurrentSheetTwoFluid", "classCurrentSheetTwoFluid.html", "classCurrentSheetTwoFluid" ],
    [ "Data", "classData.html", "classData" ],
    [ "Failed", "structFailed.html", "structFailed" ],
    [ "FluxMethod", "classFluxMethod.html", "classFluxMethod" ],
    [ "FVS", "classFVS.html", "classFVS" ],
    [ "IMEX2Arguments", "classIMEX2Arguments.html", "classIMEX2Arguments" ],
    [ "IMEX3Arguments", "classIMEX3Arguments.html", "classIMEX3Arguments" ],
    [ "InitialFunc", "classInitialFunc.html", "classInitialFunc" ],
    [ "Model", "classModel.html", "classModel" ],
    [ "OTVortexSingleFluid", "classOTVortexSingleFluid.html", "classOTVortexSingleFluid" ],
    [ "Outflow", "classOutflow.html", "classOutflow" ],
    [ "Periodic", "classPeriodic.html", "classPeriodic" ],
    [ "RK2", "classRK2.html", "classRK2" ],
    [ "RKSplit", "classRKSplit.html", "classRKSplit" ],
    [ "SaveData", "classSaveData.html", "classSaveData" ],
    [ "Simulation", "classSimulation.html", "classSimulation" ],
    [ "SRMHD", "classSRMHD.html", "classSRMHD" ],
    [ "SSP2", "classSSP2.html", "classSSP2" ],
    [ "SSP3", "classSSP3.html", "classSSP3" ],
    [ "TimeIntegrator", "classTimeIntegrator.html", "classTimeIntegrator" ],
    [ "TwoFluidEMHD", "classTwoFluidEMHD.html", "classTwoFluidEMHD" ]
];